name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  copy_with_extension:
  dev: ^1.0.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.4
